version: "3.9"
services:
  netemu:
    build: .
    privileged: true
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./profiles:/app/profiles
      - ./app.py:/app/app.py
      - ./netemu_core.py:/app/netemu_core.py
    ports:
      - "8501:8501"
